db:
  type: 'mysql'
  port: 3306
  host: 'db4free.net'
  database: 'tafelay'
  logging: false
  username: 'akash_test_2'
  password: 'akash_test_2'

server:
  port: 3000

jwt:
  secret: 'JWT_SECRET'
  expiresIn: 3600
