db:
  type: 'mysql'
  port: 3306
  host: 'remotemysql.com'
  database: 'rVduo83um9'
  logging: false
  username: 'rVduo83um9'
  password: '3zsbuYQrFE'

server: 
  port:  3000

jwt:
  secret: 'JWT_SECRET'
  expiresIn: 3600
